"""Initial migration

Revision ID: 884f77aacc9a
Revises: 
Create Date: 2026-02-09 13:02:43.166157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884f77aacc9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_appointments_customer'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_date'), table_name='appointments')
    op.drop_index(op.f('idx_conversations_session'), table_name='conversations')
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.drop_index(op.f('idx_customers_email'), table_name='customers')
    op.drop_index(op.f('idx_document_embeddings_vector'), table_name='document_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_document_metadata'), table_name='document_embeddings', postgresql_using='gin')
    op.drop_index(op.f('idx_service_history_vehicle'), table_name='service_history')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('idx_vehicles_customer'), table_name='vehicles')
    op.drop_index(op.f('idx_vehicles_vin'), table_name='vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_vehicles_vin'), 'vehicles', ['vin'], unique=False)
    op.create_index(op.f('idx_vehicles_customer'), 'vehicles', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_service_history_vehicle'), 'service_history', ['vehicle_id'], unique=False)
    op.create_index(op.f('idx_document_metadata'), 'document_embeddings', ['doc_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_document_embeddings_vector'), 'document_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_customers_email'), 'customers', ['email'], unique=False)
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_session'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('idx_appointments_date'), 'appointments', ['scheduled_date'], unique=False)
    op.create_index(op.f('idx_appointments_customer'), 'appointments', ['customer_id'], unique=False)
    # ### end Alembic commands ###
